### ISSUE TITLE
想问一下出现需要人机验证该怎么破呀

### ISSUE THREAD

**Issue by ABucket** [tanenrumu/Arknights_Checkin#10]
是用服务器ip发包过多了嘛 有什么办法可以避免吗

**Comment by Tao0Lu** [comment]
？我测试的时候只有发生验证码时会有人机验证（或者你账号有问题？）如果是“账户安全异常，请稍后再尝试。”的话，用密码或access token 登录就行（access token可以抓包获取，或者直接密码登录获取（为了安全的话，可以将本项目clone下来在本地用密码登录后获取））
如果你是在checkin.php中的话，那就难办了。
毕竟 YJ 用的是国内最大的验证码平台 极验 （这玩意腾讯都在用），破解不现实。

**Comment by ABucket** [comment]
好的好的 我去试试 感谢

**Comment by ABucket** [comment]
还是不行 是用密码登陆的， 用auth也还是需要人机验证

**Comment by Tao0Lu** [comment]
那应该就是账号问题了，我测试时登录是没有的，只有发送手机验证码的时候会有。虽然密码登录不安全（都1202年了，还不支持传哈希我也是无力吐槽）

**Comment by ABucket** [comment]
行 感谢

**Comment by ABucket** [comment]
😭![image](https://user-images.githubusercontent.com/82869104/130227990-819a99f3-2102-4fa4-863b-90578efbf944.png)

**Comment by ABucket** [comment]
😭![QQ图片20210820194033](https://user-images.githubusercontent.com/82869104/130228053-071e7f9d-100d-4205-8b16-2897dcad9bb5.png)

**Comment by ABucket** [comment]
可以麻烦您帮我抓一下极验验证码滑完之后返回到哪里吗，我已经弄出了返回值 但是不知道该返回到哪里

**Comment by Tao0Lu** [comment]
我曾尝试过，抓不到，应该不是http协议。关于极验的破解，github 上面有很多人研究过的，不过这些应该都失效了，因为极验会不停的更换加密方法（不然你当他们不要饭的吗），所以我才说这不现实。如果你只在我搭建的服务器上面登录报错，不妨你可以搭建 serverless 的云函数（不要钱）部署 [Arknights_Checkin_Serverless](https://github.com/Tao0Lu/Arknights_Checkin_Serverless) 顺便还能实现定时签到。
